# image will be published to ghcr.io/<user>/<name>
name: infidelicious-ublue
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - cockpit
      - edk2-ovmf
      - guestfs-tools
      - ifuse
      - libvirt
      - lm_sensors
      - nvidia-vaapi-driver
      - qemu-kvm
      - ramalama
      - restic
      - swtpm
      - tailscale
      - virt-install
      - virt-manager
      - virt-viewer
    remove:
      - waydroid
      - waydroid-selinux


  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - org.localsend.localsend_app

  - type: signing
