# image will be published to ghcr.io/<user>/<name>
name: infidelicious-ublue
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - cockpit
      - edk2-ovmf
      - guestfs-tools
      - ifuse
      - libvirt
      - lm_sensors
      - qemu-kvm
      - ramalama
      - restic
      - swtpm
      - tailscale
      - virt-install
      - virt-manager
      - virt-viewer
      - xorg-x11-drv-nvidia
      - xorg-x11-drv-nvidia-cuda
    remove:
      - waydroid
      - waydroid-selinux

  - type: default-flatpaks
    system:
      install:
        - org.localsend.localsend_app

  - type: signing
